name: 'commuting_insights'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - tabulate  # df.to_markdown()
    - lxml  # pd.read_html()
    - pip
    - geopandas
    - pip:
        - dash-vega-components